package com.example.albanianidverification.security

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.SecretKey
import android.util.Base64
import java.util.UUID

/**
 * ══════════════════════════════════════════════════════════════
 *  NonceManager — Replay Attack Prevention (Android Side)
 *
 *  Every request signed here becomes impossible to replay because:
 *    • The nonce is a random UUID — can only appear once in the backend cache
 *    • The timestamp must be within 60 seconds — capturing and re-sending later fails
 *    • The HMAC ties both values to a device-bound secret — another device can't forge it
 *
 *  The HMAC secret lives in Android Keystore (hardware-backed on supported devices).
 *  It cannot be extracted from the device, even by the app itself — it can only be used
 *  to compute MACs through the Keystore API.
 * ══════════════════════════════════════════════════════════════
 */
object NonceManager {

    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEY_ALIAS         = "evoting_hmac_request_signing_key"
    private const val HMAC_ALGORITHM    = "HmacSHA256"

    /**
     * Initialise the HMAC key. Call once during app startup (e.g. Application.onCreate).
     * If the key already exists it is reused — never regenerated unless explicitly rotated.
     */
    fun initialise(context: Context) {
        if (!keyExists()) {
            generateKey()
        }
    }

    /**
     * Generate a cryptographically random nonce.
     * Each call returns a new UUID — guaranteed unique per request.
     */
    fun generateNonce(): String = UUID.randomUUID().toString()

    /**
     * Produce an HMAC-SHA256 signature over the concatenation:
     *   nonce + ":" + timestamp + ":" + path
     *
     * This ties the signature to this specific request. The backend verifies that:
     *   1. The nonce has never been seen before (stored in a short-lived cache)
     *   2. The timestamp is within the 60-second acceptance window
     *   3. The HMAC matches (requires the same device-bound key)
     *
     * @param nonce     UUID generated by [generateNonce]
     * @param timestamp epoch ms as a string (use System.currentTimeMillis().toString())
     * @param path      URL path of the request (e.g. "/api/v1/auth/id-card")
     * @return Base64-encoded (no-wrap) HMAC-SHA256 signature
     */
    fun signRequest(nonce: String, timestamp: String, path: String): String {
        val message = "$nonce:$timestamp:$path"
        val mac = Mac.getInstance(HMAC_ALGORITHM, KEYSTORE_PROVIDER)
        mac.init(getOrCreateKey())
        val rawMac = mac.doFinal(message.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(rawMac, Base64.NO_WRAP)
    }

    /**
     * Returns the public bytes of the HMAC key for registration with the backend.
     * Call this once after first launch and POST it to /api/v1/auth/register-device
     * so the backend can verify future request signatures.
     *
     * IMPORTANT: The Keystore HMAC key is symmetric — you cannot export the raw key bytes.
     * Instead, share a derived "device fingerprint" (see DeviceKeyManager for asymmetric
     * proof-of-possession). This method is a stub for the registration flow.
     */
    fun getDeviceId(): String {
        // Use a stable, hardware-backed identifier. In production, derive this from
        // the Android ID combined with Play Integrity's device binding.
        return android.provider.Settings.Secure.getString(
            null, android.provider.Settings.Secure.ANDROID_ID
        ) ?: "unknown"
    }

    // ─── Private helpers ────────────────────────────────────────────────────────

    private fun keyExists(): Boolean = try {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
        keyStore.load(null)
        keyStore.containsAlias(KEY_ALIAS)
    } catch (e: Exception) {
        false
    }

    private fun generateKey() {
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_HMAC_SHA256, KEYSTORE_PROVIDER
        )
        keyGenerator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
            )
                .setKeySize(256)
                // Require user authentication for extra-sensitive ops if desired:
                // .setUserAuthenticationRequired(true)
                // .setUserAuthenticationValidityDurationSeconds(60)
                .build()
        )
        keyGenerator.generateKey()
    }

    private fun getOrCreateKey(): SecretKey {
        if (!keyExists()) generateKey()
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
        keyStore.load(null)
        return keyStore.getKey(KEY_ALIAS, null) as SecretKey
    }
}