plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("kotlin-parcelize")
}

android {
    namespace = "com.example.albanianidverification"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.albanianidverification"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            // FIX 1: Groovy syntax  →  Kotlin DSL (parentheses + explicit types)
            // Old (broken): buildConfigField "String", "API_URL", '"http://..."'
            buildConfigField("String", "API_URL", "\"http://192.168.100.58:8081/\"")
        }
        release {
            isMinifyEnabled   = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            // FIX 2: release also needs the field, otherwise BuildConfig.API_URL
            // won't compile in release builds
            buildConfigField("String", "API_URL", "\"https://api.voting.albania.gov/\"")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        viewBinding = true
        // FIX 3: BuildConfig is NOT generated by default in AGP 8+.
        // Without this, importing BuildConfig causes a compile error.
        buildConfig = true
    }

    packaging {
        resources {
            excludes += setOf(
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/license.txt",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt",
                "META-INF/notice.txt",
                "META-INF/ASL2.0",
                "META-INF/*.kotlin_module"
            )
            pickFirsts += setOf(
                "org/bouncycastle/**",
                "**.properties"
            )
        }
    }

    androidResources {
        // Prevent compression of TFLite model files for memory-mapped loading
        // (aaptOptions is deprecated in AGP 8+, androidResources is the replacement)
        noCompress += "tflite"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")

    // CameraX
    implementation("androidx.camera:camera-core:1.3.1")
    implementation("androidx.camera:camera-camera2:1.3.1")
    implementation("androidx.camera:camera-lifecycle:1.3.1")
    implementation("androidx.camera:camera-view:1.3.1")

    // ML Kit
    implementation("com.google.mlkit:text-recognition:16.0.0")
    implementation("com.google.mlkit:face-detection:16.1.6")

    // TensorFlow Lite
    implementation("org.tensorflow:tensorflow-lite:2.14.0")
    implementation("org.tensorflow:tensorflow-lite-support:0.4.4")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // Lifecycle
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")

    // JMRTD for NFC reading
    implementation("org.jmrtd:jmrtd:0.7.34") {
        exclude(group = "org.bouncycastle")
    }
    implementation("net.sf.scuba:scuba-sc-android:0.0.23") {
        exclude(group = "org.bouncycastle")
    }

    // Bouncy Castle
    implementation("org.bouncycastle:bcprov-jdk18on:1.71")

    // Networking
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
    implementation("com.squareup.retrofit2:retrofit:2.9.0")
    implementation("com.squareup.retrofit2:converter-gson:2.9.0")

    // Encrypted storage for JWT tokens
    implementation("androidx.security:security-crypto:1.1.0-alpha06")

    // QR code for vote receipt
    implementation("com.journeyapps:zxing-android-embedded:4.3.0")

    // Play Integrity API
    implementation("com.google.android.play:integrity:1.3.0")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
}